#BSUB -W 24:00
#BSUB -n 16
#BSUB -M 80000
#BSUB -R "span[ptile=16]"
#BSUB -e logs/interpret_%J.err
#BSUB -o logs/interpret_%J.out
#BSUB -q amdgpu
#BSUB -gpu "num=1"

module load bedtools/2.29.2-wrl
module load gcc/8.3.0
module load cuda/11.5
source activate maxatac-tfmodisco

cd /data/weirauchlab/team/ngun7t/maxatac

maxatac interpret \
--arch DCNN_V2 \
--sequence /users/ngun7t/opt/maxatac/data/hg38/hg38.2bit  \
--meta_file /data/weirauchlab/team/ngun7t/maxatac/meta_file_for_interpreting_LEF1.tsv \
--output /data/weirauchlab/team/ngun7t/maxatac/runs/interpreting_results/LEF1 \
--prefix interpreting_analysis \
--interpreting_cell_line D1_mesendoderm \
--weights /users/ngun7t/opt/maxatac/data/models/LEF1/LEF1_binary_revcomp99_fullModel_RR0_97.h5 \
--threads 96 \
--sample_size  5000  \
--channels  11 15