#BSUB -W 24:00
#BSUB -n 12
#BSUB -M 80000
#BSUB -R "span[hosts=1]"
#BSUB -e logs/prepare_%J.err
#BSUB -o logs/prepare_%J.out

# load modules
module load bedtools/2.29.2-wrl
module load samtools/1.6-wrl
module load pigz/2.6.0
module load ucsctools

source activate maxatac

# the main command
maxatac prepare -i /data/weirauchlab/team/ngun7t/maxatac/test_data/GM12878_CombinedLoading_1million_fragments.tsv.gz -o ./prepare_data -prefix GM12878